name: Assign PR to creator

on:
  pull_request:
    # types: [opened]

jobs:
  assign_creator:
    if: ${{ github.event.pull_request.user.login != 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    steps:
    - name: Assign PR to creator
      run: gh pr edit "${{ github.event.pull_request.html_url }}" --add-assignee "${{ github.event.pull_request.user.login }}"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}        