name: Assign PR to creator

on:
  pull_request:
    types: [opened]

jobs:
  assign_creator:
    runs-on: ubuntu-latest
    steps:
    - name: Assign PR to creator
      run: gh pr edit $PR_NUMBER --add-assignee $CREATOR
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PR_NUMBER: $${{ github.event.pull_request.number }}
        CREATOR: ${{ github.event.pull_request.user.login }}